AllCops:
  NewCops: enable
  SuggestExtensions: false
  DefaultFormatter: fuubar

  # Output extra information for each offense to make it easier to diagnose:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

  # RuboCop enforces rules depending on the oldest version of Ruby which
  # your project supports:
  TargetRubyVersion: 3.1

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120

# The DSL for RSpec and the gemspec file make it very hard to limit block length
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '*.gemspec'

Metrics/ModuleLength:
  CountAsOne: ['hash']

Metrics/ClassLength:
  CountAsOne: ['hash']

Style/AsciiComments:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Naming/FileName:
  Exclude: ['lib/simplecov-rspec.rb', 'spec/simplecov-rspec_spec.rb']
