name: Semver PR Label

on:
  pull_request:
    branches: [main]

    # This workflow will trigger when pull requests to the main branch are opened,
    # synchronize, reopened, labeled, or unlabeled.

    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  semver_pr_label:
    name: Semver PR Label
    runs-on: ubuntu-latest

    steps:
      - name: Check that a semver label is present on the PR
        if: github.event_name == 'pull_request'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major-change,minor-change,patch-change,internal-change
          repo_token: ${{ secrets.GITHUB_TOKEN }}
